# NOTE: You need to have Nerd fonts attached to your font
# https://www.nerdfonts.com/#home

# The newline at the start of the prompt
add_newline = true

# Overwrite a default_prompt_order and use custom prompt_order
prompt_order=[
	"time",
	"jobs",
	"hostname",
	"directory",
	"git_branch",
	"git_commit",
	"git_state",
	"git_status",
	#
	"line_break",
	"battery",
	"memory_usage",
	"package",
	"nodejs",
	"custom.npm",
	"custom.yarn",
	"cmd_duration",
	#
	"line_break",
	"username",
	"character",
]

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Prompt
[time]
	format = "ğŸ•°ï¸[%T]"
	style = "fg:black bg:white"
	utc_time_offset="local"
	disabled = false

[jobs]
	symbol = "âš ï¸ï€“âš ï¸"
	threshold = 1
	style="fg:bright-white bg:red"
	disabled="true"

[hostname]
	ssh_only = true
	prefix = "ğŸ–¥ï¸"
	suffix = ""
	trim_at = ".companyname.com"
	style = "fg:bright-white bg:purple"
	disabled = false

[directory]
	truncation_length = 3
	truncate_to_repo = true
	prefix = "in ğŸ“‚: "
	style = "purple"
	fish_style_pwd_dir_length	= 5
	use_logical_path = true
	disabled = false

[git_branch]
	symbol = "\ue725 " # îœ¥
	truncation_length = 0
	truncation_symbol = ""
	style = "bright-cyan"
	disable = false

[git_commit]
	commit_hash_length = 5
	prefix = "ğŸš¨DETACHED: "
	suffix = ""
	style = "bright-red"
	only_detached = true
	disabled = false

[git_state]
	rebase = "REBASING"
	merge = "MERGING"
	revert = "REVERTING"
	cherry_pick = "ğŸ’ PICKING"
	bisect = "BISECTING"
	am = "AM"
	am_or_rebase = "AM/REBASE"
	progress_divider = " of "
	style = "red"
	disable = false

[git_status]
	show_sync_count = true
	prefix = "\uf1d3" # ï‡“
	suffix = ""
	style = ""
	disabled = false
	# Conflicted
	conflicted.value = "ğŸš©C:"
	conflicted.style = "bright-red"
	conflicted_count.enabled = true
	conflicted_count.style = "bright-red"
	# Diverged
	diverged.value = "ï½î‚ D"
	diverged.style = "bright-red"
	# Ahead
	ahead.value = "|â‡¡î‚ A:"
	ahead.style = "bright-blue"
	# Behind
	behind.value = "|â‡£î‚ B:"
	behind.style = "bright-yellow"
	# Stashed
	stashed.value = "î˜¡\uf01cS:" # ï€œ
	stashed.style = ""
	stashed_count.enabled = true
	stashed_count.style = ""
	# Deleted
	deleted.value = "î˜¡\uf48eD:" # ï’
	deleted.style = "bright-red"
	deleted_count.enabled = true
	deleted_count.style = "bright-red"
	# Renamed
	renamed.value = "î˜¡\uf45aR:" # ï‘š
	renamed.style = "bright-purple"
	renamed_count.enabled = true
	renamed_count.style = "bright-purple"
	# Modified
	modified.value = "î˜¡\uf459M:" # ï‘™
	modified.style ="bright-yellow"
	modified_count.enabled = true
	modified_count.style = "bright-yellow"
	# Staged
	staged.value = "î˜¡\uf457S:" # ï‘—
	staged.style = "bright-green"
	staged_count.enabled = true
	staged_count.style = "bright-green"
	# Untracked
	untracked.value = "î˜¡\uf29cU:" # ïŠœ
	untracked.style = "bright-red"
	untracked_count.enabled = true
	untracked_count.style = "bright-red"

# line_break
[battery]
	full_symbol = "ï•¸:"
	charging_symbol = "ï–ƒ:"
	discharging_symbol = "ï–‚:"
	disabled = "false"
	[[battery.display]]
	threshold = 50
	style = "fg:bright-white bg:red"
	[[battery.display]]
	threshold = 75
	style = "fg:black bg:bright-yellow"
	[[battery.display]]
	threshold = -1
	style = "bright-green"

[memory_usage]
	show_percentage = true
	show_swap = true
	threshold = 75
	symbol = "ï¡š:"
	separator = "|"
	style = "bright-blue"
	disabled = false

[package]
	symbol = "ï£– "
	style = "yellow"
	display_private = "true"
	disabled = false

[nodejs]
	symbol = "îœ˜ "
	style = "bright-green"
	disabled = false

[custom.npm]
	symbol = "\ue71e " # îœ
	prefix = "î˜¡" # î˜¡
	command = "npm -v"
	files = ["package.json"]
	style = "red"
	disabled = false

[custom.yarn]
	symbol = "\uf61a " # ï˜š
	prefix = "î˜¡" # î˜¡
	command = "yarn -v"
	files = ["yarn.lock"]
	style = "cyan"
	disabled = false

[cmd_duration]
	min_time = 100
	show_milliseconds = true
	style = ""
	prefix = "| Last operation ï‰“:"
	disabled = false

# Line_break
[username]
	style_root = "red"
	style_user = "bright-purple"
	show_always = false
	disabled = false

[character]
	symbol = "â¯"
	error_symbol = "\uf00d" # ï€
	use_symbol_for_status = true
	# vicmd_symbol = " [îŸ…]ï‚©"
	style_success = ""
	style_failure = "bright-red"
	disabled = "false"
